### PR TITLE
Generate priv validator on each node

### PR DESCRIPTION
**Pull request by melekes**
Pros:
- we do not share private validator with anybody (more secure)

Cons:
- during start, all pods wait until genesis file is formed (see genesis init container)
- genesis init container runs in a privileged mode https://kubernetes.io/docs/user-guide/security-context

Implementation details: 
every pod has a `genesis` init container, which 1) generates private validator 2) writes public key to the host path (`genesisdir`) https://kubernetes.io/docs/user-guide/volumes/#hostpath and waits until other pods will do the same

### CODE REVIEW

**Comment by melekes** [comment]
Damn, pods in StatefulSet are created sequentially https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#ordered-pod-creation. This could be a problem...

**Comment by melekes** [comment]
Scaling up/down also works now! with `kubectl scale --replicas=5 statefulset tm` ❤️ 💚 💛

**Comment by ebuchman** [comment]
Amazing. This is exactly what we're going to want. Does this only work right now if all pods are on the same physical machine? Or does kubernetes provide some other kind of abstraction, like is it using etcd under the hood? Ultimately, I envisioned we would build something like this using etcd or consul (eventually tendermint itself) where nodes create their privkey, post their pubkey to the etcd, wait for all the pubkeys, then pull them and generate the genesis file. So this is a great start towards that paradigm!

**Comment by melekes** [comment]
Does this only work right now if all pods are on the same physical machine?

Yes (I haven't checked, but I am pretty sure). But `hostsDir` could be swapped with NFS dir and it will work smoothly. Not sure what is best here: etcd or plain NFS server.

**Comment by melekes** [comment]
Actually, you just gave me an idea, which I think is brilliant (no NFS/etcd/.. required). Why not just serve public key on some port? When all public keys become available, we create genesis file on each node (time/chain-id is hard coded in config).

**Comment by melekes** [comment]
Struggling with two problems right now: 1) Nginx returns `403 Permission Denied` when I want to get `/pub_key.json` and 2) pods are not seeing each other (maybe because there are not fully ready?)

**Comment by melekes** [comment]
solved (1) by upgrading the minikube https://github.com/kubernetes/minikube/issues/1067

**Comment by ebuchman** [comment]
thats so cool. so you just start an nginx container with every pod that serves the pubkey? brilliant!

**Pull request merged**
